//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Haiyan Ma @SwiftTsubame
//

import Foundation

protocol ___VARIABLE_productName:identifier___Presentation: class{
}

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___Presentation {

    private let interactor: ___VARIABLE_productName: identifier___Interaction
    private let router: ___VARIABLE_productName: identifier___Routing

    init(interactor: ___VARIABLE_productName: identifier___Interaction,
        router: ___VARIABLE_productName: identifier___Routing) {
        self.interactor = interactor
        self.router = router
    }
}
