//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Haiyan Ma @swiftTsubame
//

import UIKit

protocol ___VARIABLE_productName:identifier___Viewing: class{
    var presenter: ___VARIABLE_productName:identifier___Presentation? { get set }
}

class ___VARIABLE_productName:identifier___ViewController: UIViewController, ___VARIABLE_productName:identifier___Viewing {

	var presenter: ___VARIABLE_productName:identifier___Presentation?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
}
