//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Haiyan Ma @swiftTsubame
//

import UIKit

protocol ___VARIABLE_productName:identifier___Routing: class {
    
}
class ___VARIABLE_productName:identifier___Router: ___VARIABLE_productName:identifier___Routing {
    private let container: ___VARIABLE_productName: identifier___DependencyContainer
    
    init(container: ___VARIABLE_productName: identifier___DependencyContainer = ___VARIABLE_productName:identifier___DependencyContainer()) {
        self.container = container
    }
}
