//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Haiyan Ma @swiftTsubame
//

import Foundation

protocol ___VARIABLE_productName:identifier___Interaction: class {
}

class ___VARIABLE_productName:identifier___Interactor: ___VARIABLE_productName:identifier___Interaction {
}
