//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Haiyan Ma @SwiftTsubame
//

import Foundation

protocol ___VARIABLE_productName:identifier___Presentation: class {
    var interactor: ___VARIABLE_productName: identifier___Interaction { get }
    var router: ___VARIABLE_productName: identifier___Routing { get }
}

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___Presentation {

    var interactor: ___VARIABLE_productName: identifier___Interaction
    var router: ___VARIABLE_productName: identifier___Routing

    init(interactor: ___VARIABLE_productName: identifier___Interaction,
         router: ___VARIABLE_productName: identifier___Routing) {
        self.interactor = interactor
        self.router = router
    }
}
