//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Haiyan Ma @swiftTsubame
//

import UIKit

class ___VARIABLE_productName:identifier___DependencyContainer {
    private lazy var interactor = ___VARIABLE_productName:identifier___Interactor()
    private lazy var router = ___VARIABLE_productName:identifier___Router()
    private lazy var presenter = ___VARIABLE_productName:identifier___Presenter(interactor: interactor, router: router)
    
    func createModule() -> UIViewController {
        let view = ___VARIABLE_productName:identifier___ViewController(nibName: nil, bundle: nil)
        view.presenter = presenter
        return view
    }
}

